### ISSUE TITLE
Changes required after code review of week 4

### ISSUE THREAD

**Issue by nhoyle-unsw** [nhoyle-unsw/learn-encryption-with-python#20]
Is this required?

_Originally posted by @mhio in https://github.com/nhoyle-unsw/learn-encryption-with-python/pull/19#r718051741_

**Comment by nhoyle-unsw** [comment]
see pull request #19 for details of the review and subsequent changes.

**Comment by mhio** [comment]
What a footnote[^1]

Some more text so I can see a link working

Yeah

[^1]: A foootnote reference
